import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { StoreProvider } from "../store/StoreContext";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "block",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Laguna Lake Development Authority",
  description: "Generated by laguna Lake Development Authority",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.variable} antialiased`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
